apiVersion: v1
kind: Template
labels:
  demo: microservices-demo
metadata:
  annotations:
    description: Socks Shop demo microservices application buildconfigs template
    iconClass: icon-go
    tags: microservice,go
  name: user-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: user
    labels:
      comp-required: "true"
      app: user
  spec:
    tags:
    - name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: user
    labels:
      comp-required: "true"
      app: user
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: user:latest
    source:
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URI}
      type: Git
    triggers:
    - github:
        secret: c2VjcmV1dmFsdWUx
      type: GitHub
    strategy:
      sourceStrategy:
        - env:
          - name: APP_URI
            value: ${APP_URI}
        forcePull: false
        from:
          kind: ImageStreamTag
          name: s2i-centos7-golang:latest
          namespace: gl-oc-demo-ci-cd
      type: Source
    resources:
      limits:
        cpu: 500m
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "1Gi"
parameters:
- name: APP_URI
  required: true
  value: github.com/andriy-gnennyy-gl/oc-demo-ci-cd-user
- description: Git source URI for application
  displayName: Git source repository
  name: GIT_URI
  required: true
  value: https://github.com/andriy-gnennyy-gl/oc-demo-ci-cd-user
- description: Git branch/tag reference
  displayName: Git branch/tag reference
  name: GIT_REF
  required: true
  value: dev