apiVersion: v1
kind: Template
labels:
  demo: microservices-demo
metadata:
  annotations:
    description: Socks Shop demo microservices application buildconfigs template
    iconClass: icon-mongodb
    tags: microservice,mongodb
  name: orders-db-deployments
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: orders-db
    labels:
      app: orders-db
      comp-required: "true"
  spec:
    replicas: 1
    selector:
      app: orders-db
      deploymentconfig: orders-db
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: orders-db
          deploymentconfig: orders-db
      spec:
        containers:
        - name: orders-db
          image: mongo
          ports:
          - name: mongo
            containerPort: 27017
          resources:
            limits:
              cpu: 300m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 300Mi
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
        volumes:
          - name: tmp-volume
            emptyDir:
              medium: Memory
        nodeSelector:
          beta.kubernetes.io/os: linux
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: orders-db
      comp-required: "true"
    name: orders-db
  spec:
    ports:
    - name: 27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: orders-db
      deploymentconfig: orders-db
parameters:
- description: Hostname suffix used for routes
  displayName: Hostname suffix used for routes
  name: HOSTNAME_SUFFIX
  required: false