apiVersion: v1
kind: Template
labels:
  demo: microservices-demo
metadata:
  annotations:
    description: Socks Shop demo microservices application buildconfigs template
    iconClass: icon-mysql
    tags: microservice,mysql
  name: catalogue-db-deployments
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: catalogue-db
    labels:
      app: catalogue-db
      comp-required: "true"
  spec:
    replicas: 1
    selector:
      app: catalogue-db
      deploymentconfig: catalogue-db
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: catalogue-db
          deploymentconfig: catalogue-db
      spec:
        containers:
        - name: catalogues-db
          image: weaveworksdemos/catalogue-db:0.3.0
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: fake_password
          - name: MYSQL_DATABASE
            value: socksdb
          ports:
          - name: mysql
            containerPort: 3306
          resources:
            limits:
              cpu: 300m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 300Mi
        nodeSelector:
          beta.kubernetes.io/os: linux
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: catalogue-db
      comp-required: "true"
    name: catalogue-db
  spec:
    ports:
    - port: 3306
      targetPort: 3306
    selector:
      deploymentconfig: catalogue-db
parameters:
- description: Hostname suffix used for routes
  displayName: Hostname suffix used for routes
  name: HOSTNAME_SUFFIX
  required: false