apiVersion: v1
kind: Template
labels:
  demo: microservices-demo
metadata:
  annotations:
    description: Socks Shop demo microservices application buildconfigs template
    iconClass: icon-golang
    tags: microservice,golang
  name: payment-deployments
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: payment
    labels:
      app: payment
      comp-required: "true"
  spec:
    replicas: 1
    selector:
      app: payment
      deploymentconfig: payment
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: payment
          deploymentconfig: payment
      spec:
        containers:
        - name: payment
          image: weaveworksdemos/payment:0.4.3
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 99m
              memory: 100Mi
          ports:
          - containerPort: 80
          securityContext:
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: payment
      comp-required: "true"
    name: payment
  spec:
    ports:
    - port: 80
      targetPort: 80
    selector:
      deploymentconfig: payment
parameters:
- description: Hostname suffix used for routes
  displayName: Hostname suffix used for routes
  name: HOSTNAME_SUFFIX
  required: false