apiVersion: v1
kind: Template
labels:
  demo: microservices-demo
metadata:
  annotations:
    description: Socks Shop demo microservices application buildconfigs template
    iconClass: icon-nodejs
    tags: microservice,nodejs
  name: dev-front-end-deployments
objects:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: default_edit
  roleRef:
    name: view
  subjects:
  - kind: ServiceAccount
    name: default
# UI
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: dev-front-end
    labels:
      app: dev-front-end
      comp-required: "true"
  spec:
    replicas: 1
    selector:
      app: dev-front-end
      deploymentconfig: dev-front-end
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: dev-front-end
          deploymentconfig: dev-front-end
      spec:
        containers:
        - env:
          - name: COOLSTORE_GW_ENDPOINT
            value: http://gw-${HOSTNAME_SUFFIX}
          - name: HOSTNAME_HTTP
            value: web-ui:8080
          image: dev-front-end
          imagePullPolicy: Always
          name: dev-front-end
          ports:
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            failureThreshold: 10
            exec:
              command:
                - curl
                - '-f'
                - 'http://localhost:8080'
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
          readinessProbe:
            failureThreshold: 10
            exec:
              command:
                - curl
                - '-f'
                - 'http://localhost:8080'
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - dev-front-end
        from:
          kind: ImageStreamTag
          name: dev-front-end:${APP_VERSION}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: dev-front-end
      comp-required: "true"
    name: dev-front-end
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: dev-front-end
- apiVersion: v1
  kind: Route
  metadata:
    name: dev-front-end
    labels:
      app: dev-front-end
      comp-required: "true"
  spec:
    host: dev-front-end-${HOSTNAME_SUFFIX}
    to:
      kind: Service
      name: dev-front-end
parameters:
- description: Application image version to be deployed (imagestreams should exist)
  displayName: Image version
  name: APP_VERSION
  required: true
  value: latest
- description: Hostname suffix used for routes
  displayName: Hostname suffix used for routes
  name: HOSTNAME_SUFFIX
  required: true