apiVersion: v1
kind: Template
labels:
  demo: microservices-demo
metadata:
  annotations:
    description: Socks Shop demo microservices application buildconfigs template
    iconClass: icon-java
    tags: microservice,java
  name: shipping-deployments
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: shipping
    labels:
      app: shipping
      comp-required: "true"
  spec:
    replicas: 1
    selector:
      app: shipping
      deploymentconfig: shipping
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: shipping
          deploymentconfig: shipping
      spec:
        containers:
        - name: shipping
          image: weaveworksdemos/shipping:0.4.8
          env:
          - name: ZIPKIN
            value: zipkin.jaeger.svc.cluster.local
          - name: JAVA_OPTS
            value: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
          resources:
            limits:
              cpu: 300m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 80
          securityContext:
            readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: shipping
      comp-required: "true"
    name: shipping
  spec:
    ports:
    - port: 80
      targetPort: 80
    selector:
      name: shipping
      deploymentconfig: shipping
parameters:
- description: Hostname suffix used for routes
  displayName: Hostname suffix used for routes
  name: HOSTNAME_SUFFIX
  required: false