apiVersion: v1
kind: Template
labels:
  demo: microservices-demo
metadata:
  annotations:
    description: Socks Shop demo microservices application buildconfigs template
    iconClass: icon-rabbitmq
    tags: microservice,rabbitmq
  name: rabbitmq-deployments
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: rabbitmq
    labels:
      app: rabbitmq
      comp-required: "true"
  spec:
    replicas: 1
    selector:
      app: rabbitmq
      deploymentconfig: rabbitmq
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: rabbitmq
          deploymentconfig: rabbitmq
        annotations:
          prometheus.io/scrape: "false"
      spec:
        containers:
        - name: rabbitmq
          image: rabbitmq:3.6.8-management
          ports:
          - name: management
            containerPort: 15672
          - name: rabbitmq
            containerPort: 5672
          resources:
            limits:
              cpu: 300m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 300Mi
          securityContext:
            readOnlyRootFilesystem: true
        - name: rabbitmq-exporter
          image: kbudde/rabbitmq-exporter
          ports:
          - containerPort: 9090
            name: exporter
        nodeSelector:
          beta.kubernetes.io/os: linux
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rabbitmq
      comp-required: "true"
    name: rabbitmq
  spec:
    ports:
    - port: 5672
      name: rabbitmq
      targetPort: 5672
    - port: 9090
      name: exporter
      targetPort: exporter
      protocol: TCP
    selector:
      deploymentconfig: rabbitmq
parameters:
- description: Hostname suffix used for routes
  displayName: Hostname suffix used for routes
  name: HOSTNAME_SUFFIX
  required: false